name: "Repository Metrics Monitor"
description: "Creates graphs of monitored values to display them using GitHub Pages."
inputs:
  token:
    description: "GitHub Token for pushing the doc changes"
    required: true;
  key:
    required: true
  value:
    required: true
runs:
  using: "node12"
  main: "index.js"
