name: Build and Test

on:
  - push

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Build and Test
        run: |
          yarn
          yarn build
          yarn test
