name: Update Monitor

on:
  push:
    branches:
      - master

jobs:
  UpdateMonitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Calculate project metrics
        id: projectmetrics
        run: |
          yarn
          yarn build
          yarn test
          SRC_SIZE=($(du -s dist/))
          SRC_FILES_COUNT=($(find src -type f | wc -l))
          echo "::set-output name=code_size::$SRC_SIZE"
          echo "::set-output name=code_files_count:$SRC_FILES_COUNT"
      - uses: floric/repo-monitor-action@v1.7.3
        name: Update Report for Files Size
        id: update-file-size
        with:
          key: code-size
          value: ${{ steps.projectmetrics.outputs.code_size }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: floric/repo-monitor-action@v1.7.3
        name: Update Report for Files Count
        id: update-files-count
        with:
          key: files-count
          value: ${{ steps.projectmetrics.outputs.code_files_count }}
          token: ${{ secrets.GITHUB_TOKEN }}
