name: Update Monitor

on:
  push:
    branches:
      - master

jobs:
  UpdateMonitor:
    runs-on: ubuntu-latest
    steps:
      - uses: floric/repo-monitor-action@v1.1.0
        with:
          key: bundle-size
          value: 1
          token: ${{ secrets.ACCESS_TOKEN }}
