name: Update Monitor

on:
  push:
    branches:
      - master

jobs:
  UpdateMonitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Calculate lines of code
        run: |
          SIZE=($(du -s dist/))
          echo "::set-env name=CODE_SIZE::$SIZE"
      - uses: floric/repo-monitor-action@v1.2.6
        name: Update Report
        with:
          key: code-size
          value: $CODE_SIZE
          token: ${{ secrets.ACCESS_TOKEN }}
