name: Update Monitor

on:
  create:
    tags:
      - v*

jobs:
  UpdateMonitor:
    runs-on: ubuntu-latest
    steps:
      - uses: floric/repo-monitor-action@v0.0.13
        with:
          key: bundle-size
          value: 1
          token: ${{ secrets.ACCESS_TOKEN }}
